#!/bin/bash
if [ "$#" -ne 2 ]; then
    echo "I need to know dimension (2 = 2D, 3 = 3D ) and number of files"
	exit
fi
D=$1
N=$2
echo "N $N"

echo "unset key;  unset tics" > gp
for (( i = 0 ; i < $N; i++ )) do
M=75;
if (( i == 0 )) 
then M=20;
fi
for (( j = 0 ; j < $M ; j++ )) do 
if [ $D -eq 2 ]; then 
echo "plot 'M_$i' w lines " >> gp
else
echo "splot 'M_$i' u 1:2:3 w lines " >> gp
fi

done
done
echo "pause -1 " >> gp
 


