#!/bin/bash

file=$1
file2=$2
col=$3
pal=$4
echo 'using file ' $file $file2





echo " set term postscript enhanced eps solid color " > gp
echo "load '~/gnuplot-palettes/$pal.pal' " >> gp
echo " stats '$file' u $col" >> gp
echo " set cbtics add (STATS_min , STATS_max)" >> gp
echo " set cbrange [STATS_min : STATS_max]" >> gp
echo " unset border; unset xtic; unset ytics; unset key; set view 0,0; set colorbox noborder; " >> gp
echo " set style line 10 lt rgb '#252525' lw 1.5 pt 6" >> gp
echo " set format cb '%.1f'; set cblabel font '18' " >> gp
echo " splot '$file' u 1:2:3:$col w l lw 3.5 palette; " >> gp
echo " replot '$file2' u 1:2:3 w l ls 10; " >> gp
echo " set output 'colorplot.eps' ; replot; set output;" >> gp

